# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/10f022b5-943f-47c3-8e2c-588bda93f425";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" "ssd" "discard=async" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/10f022b5-943f-47c3-8e2c-588bda93f425";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:3" "noatime" "ssd" "discard=async" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/10f022b5-943f-47c3-8e2c-588bda93f425";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:3" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/609dd9b6-ae03-4968-9df9-42e40c3aff7c";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" "ssd" "discard=async" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/workspaces" =
    {
      device = "/dev/disk/by-uuid/609dd9b6-ae03-4968-9df9-42e40c3aff7c";
      fsType = "btrfs";
      options = [ "subvol=@workspaces" "compress=zstd:3" "noatime" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/41DC-1183";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # swapDevices = [
  #   {
  #     device = "/var/lib/swapfile";
  #     size = 4096;
  #   }
  # ];

  zramSwap = {
    enable = true;
    memoryPercent = 100;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
