name: "Nix CI"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: "Check and Build Nix Flakes"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: pbcdev
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build System Configuration
        run: |
          nix build .#nixosConfigurations.default.config.system.build.toplevel --accept-flake-config

      - name: Build Default Package
        run: nix build .#defaultPackage.x86_64-linux --dry-run
        continue-on-error: true
